sonar.projectKey=lyhost-frontend
sonar.projectName=lyhost-frontend
sonar.projectVersion=1.0


sonar.sources=src
sonar.tests=src
sonar.test.inclusions=\
  src/app/presentation/tenant/features/settings/pages/tenant-profile/tenant-profile.spec.ts,\
  src/app/presentation/tenant/features/incidents/pages/incident-report-list/incident-report-list.spec.ts,\
  src/app/presentation/tenant/features/incidents/pages/edit-incident-report/edit-incident-report.spec.ts,\
  src/app/presentation/tenant/features/incidents/pages/create-incident-report/create-incident-report.spec.ts,\
  src/app/domain/tenant/incident-report/use-cases/update-incident-report.use-case.spec.ts,\
  src/app/domain/tenant/incident-report/use-cases/create-incident-report.use-case.spec.ts,\
  src/app/domain/tenant/incident-report/use-cases/get-incident-reports.use-case.spec.ts,\
  src/app/domain/tenant/tenant/use-cases/get-tenant-profile.use-case.spec.ts,\
  src/app/domain/tenant/tenant/use-cases/update-tenant-profile.use-case.spec.ts,\
  src/app/infrastructure/tenant/tenant/tenant.repository.impl.spec.ts,\
  src/app/infrastructure/tenant/incident-report/incident-report.repository.impl.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lymon-frontend/lcov.info,coverage/scope/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lymon-frontend/lcov.info,coverage/scope/lcov.info

sonar.inclusions=\
  src/app/domain/tenant/tenant/use-cases/get-tenant-profile.use-case.ts,\
  src/app/domain/tenant/tenant/use-cases/update-tenant-profile.use-case.ts,\
  src/app/domain/tenant/incident-report/use-cases/get-incident-reports.use-case.ts,\
  src/app/domain/tenant/incident-report/use-cases/update-incident-report.use-case.ts,\
  src/app/domain/tenant/incident-report/use-cases/create-incident-report.use-case.ts,\
  src/app/domain/tenant/tenant/tenant.repository.ts,\
  src/app/domain/tenant/incident-report/incident-report.repository.ts,\
  src/app/infrastructure/tenant/tenant/tenant.repository.impl.ts,\
  src/app/infrastructure/tenant/incident-report/incident-report.repository.impl.ts,\
  src/app/presentation/tenant/features/settings/pages/tenant-profile/tenant-profile.ts,\
  src/app/presentation/tenant/features/incidents/pages/incident-report-list/incident-report-list.ts,\
  src/app/presentation/tenant/features/incidents/pages/edit-incident-report/edit-incident-report.ts,\
  src/app/presentation/tenant/features/incidents/pages/create-incident-report/create-incident-report.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.d.ts,**/seeds/**
sonar.coverage.exclusions=**/*.spec.ts,**/main.ts,**/*.module.ts,**/seeds/**
sonar.sourceEncoding=UTF-8
